-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- SCHOOLS Table
CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    levels TEXT NOT NULL, -- e.g., "1-8", "1-12"
    is_priority BOOLEAN DEFAULT FALSE,
    ratio TEXT DEFAULT '60/40', -- "60/40" or "65/35"
    sections TEXT[] DEFAULT ARRAY['A'],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TEACHERS Table
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ASSIGNMENTS Table (Relación Docente-Escuela)
CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE NOT NULL,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE NOT NULL,
    role TEXT NOT NULL, -- "DOCENTE DE AULA", "PIE", etc.
    contract_hours INTEGER NOT NULL CHECK (contract_hours > 0),
    type TEXT NOT NULL, -- "TITULAR", "CONTRATA"
    active_subventions TEXT[] DEFAULT '{}', -- ["PIE", "SEP"]
    blocked_days TEXT[] DEFAULT '{}', -- ["Lunes", "Martes"]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- SCHEDULES Table (Bloques horarios)
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE NOT NULL,
    course_name TEXT NOT NULL, -- "1° Básico A"
    day TEXT NOT NULL, -- "Lunes"
    block_index INTEGER NOT NULL, -- 1 to 10+
    subject_name TEXT NOT NULL,
    subject_color TEXT,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(school_id, course_name, day, block_index)
);

-- VALIDATION FUNCTION: 44 HOURS LIMIT
CREATE OR REPLACE FUNCTION check_44_hours_limit()
RETURNS TRIGGER AS $$
DECLARE
    total_hours INTEGER;
BEGIN
    -- Calculate total hours for the teacher including the new/updated record
    SELECT COALESCE(SUM(contract_hours), 0)
    INTO total_hours
    FROM assignments
    WHERE teacher_id = NEW.teacher_id
    AND id != NEW.id; -- Exclude current record if updating

    IF (total_hours + NEW.contract_hours) > 44 THEN
        RAISE EXCEPTION 'Validation Error: Teacher cannot exceed 44 contract hours per week. Current: %, New: %, Total: %', total_hours, NEW.contract_hours, (total_hours + NEW.contract_hours);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER FOR 44 HOURS
CREATE TRIGGER trigger_check_44_hours
BEFORE INSERT OR UPDATE ON assignments
FOR EACH ROW
EXECUTE FUNCTION check_44_hours_limit();

-- POLICIES (Simple RLS for now - open access or authenticated)
ALTER TABLE schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- Allow public read/write for this demo context (User should lock this down in production)
CREATE POLICY "Public Access Schools" ON schools FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Teachers" ON teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Assignments" ON assignments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Schedules" ON schedules FOR ALL USING (true) WITH CHECK (true);
