// Constantes para cálculo de horas según Ley 20.903 (Carrera Docente)

export const MAX_HORAS = 44;
export const MIN_HORAS = 1;

export interface TablaEntry {
  horasLectivas: number;
  horasNoLectivas: number;
}

// Tabla 60/40 - 60% lectivas, 40% no lectivas
export const TABLA_60_40: Record<number, TablaEntry> = {
  1: { horasLectivas: 1, horasNoLectivas: 0 },
  2: { horasLectivas: 1, horasNoLectivas: 1 },
  3: { horasLectivas: 2, horasNoLectivas: 1 },
  4: { horasLectivas: 2, horasNoLectivas: 2 },
  5: { horasLectivas: 3, horasNoLectivas: 2 },
  6: { horasLectivas: 4, horasNoLectivas: 2 },
  7: { horasLectivas: 4, horasNoLectivas: 3 },
  8: { horasLectivas: 5, horasNoLectivas: 3 },
  9: { horasLectivas: 5, horasNoLectivas: 4 },
  10: { horasLectivas: 6, horasNoLectivas: 4 },
  11: { horasLectivas: 7, horasNoLectivas: 4 },
  12: { horasLectivas: 7, horasNoLectivas: 5 },
  13: { horasLectivas: 8, horasNoLectivas: 5 },
  14: { horasLectivas: 8, horasNoLectivas: 6 },
  15: { horasLectivas: 9, horasNoLectivas: 6 },
  16: { horasLectivas: 10, horasNoLectivas: 6 },
  17: { horasLectivas: 10, horasNoLectivas: 7 },
  18: { horasLectivas: 11, horasNoLectivas: 7 },
  19: { horasLectivas: 11, horasNoLectivas: 8 },
  20: { horasLectivas: 12, horasNoLectivas: 8 },
  21: { horasLectivas: 13, horasNoLectivas: 8 },
  22: { horasLectivas: 13, horasNoLectivas: 9 },
  23: { horasLectivas: 14, horasNoLectivas: 9 },
  24: { horasLectivas: 14, horasNoLectivas: 10 },
  25: { horasLectivas: 15, horasNoLectivas: 10 },
  26: { horasLectivas: 16, horasNoLectivas: 10 },
  27: { horasLectivas: 16, horasNoLectivas: 11 },
  28: { horasLectivas: 17, horasNoLectivas: 11 },
  29: { horasLectivas: 17, horasNoLectivas: 12 },
  30: { horasLectivas: 18, horasNoLectivas: 12 },
  31: { horasLectivas: 19, horasNoLectivas: 12 },
  32: { horasLectivas: 19, horasNoLectivas: 13 },
  33: { horasLectivas: 20, horasNoLectivas: 13 },
  34: { horasLectivas: 20, horasNoLectivas: 14 },
  35: { horasLectivas: 21, horasNoLectivas: 14 },
  36: { horasLectivas: 22, horasNoLectivas: 14 },
  37: { horasLectivas: 22, horasNoLectivas: 15 },
  38: { horasLectivas: 23, horasNoLectivas: 15 },
  39: { horasLectivas: 23, horasNoLectivas: 16 },
  40: { horasLectivas: 24, horasNoLectivas: 16 },
  41: { horasLectivas: 25, horasNoLectivas: 16 },
  42: { horasLectivas: 25, horasNoLectivas: 17 },
  43: { horasLectivas: 26, horasNoLectivas: 17 },
  44: { horasLectivas: 26, horasNoLectivas: 18 },
};

// Tabla 65/35 - 65% lectivas, 35% no lectivas
export const TABLA_65_35: Record<number, TablaEntry> = {
  1: { horasLectivas: 1, horasNoLectivas: 0 },
  2: { horasLectivas: 1, horasNoLectivas: 1 },
  3: { horasLectivas: 2, horasNoLectivas: 1 },
  4: { horasLectivas: 3, horasNoLectivas: 1 },
  5: { horasLectivas: 3, horasNoLectivas: 2 },
  6: { horasLectivas: 4, horasNoLectivas: 2 },
  7: { horasLectivas: 5, horasNoLectivas: 2 },
  8: { horasLectivas: 5, horasNoLectivas: 3 },
  9: { horasLectivas: 6, horasNoLectivas: 3 },
  10: { horasLectivas: 7, horasNoLectivas: 3 },
  11: { horasLectivas: 7, horasNoLectivas: 4 },
  12: { horasLectivas: 8, horasNoLectivas: 4 },
  13: { horasLectivas: 8, horasNoLectivas: 5 },
  14: { horasLectivas: 9, horasNoLectivas: 5 },
  15: { horasLectivas: 10, horasNoLectivas: 5 },
  16: { horasLectivas: 10, horasNoLectivas: 6 },
  17: { horasLectivas: 11, horasNoLectivas: 6 },
  18: { horasLectivas: 12, horasNoLectivas: 6 },
  19: { horasLectivas: 12, horasNoLectivas: 7 },
  20: { horasLectivas: 13, horasNoLectivas: 7 },
  21: { horasLectivas: 14, horasNoLectivas: 7 },
  22: { horasLectivas: 14, horasNoLectivas: 8 },
  23: { horasLectivas: 15, horasNoLectivas: 8 },
  24: { horasLectivas: 16, horasNoLectivas: 8 },
  25: { horasLectivas: 16, horasNoLectivas: 9 },
  26: { horasLectivas: 17, horasNoLectivas: 9 },
  27: { horasLectivas: 18, horasNoLectivas: 9 },
  28: { horasLectivas: 18, horasNoLectivas: 10 },
  29: { horasLectivas: 19, horasNoLectivas: 10 },
  30: { horasLectivas: 20, horasNoLectivas: 10 },
  31: { horasLectivas: 20, horasNoLectivas: 11 },
  32: { horasLectivas: 21, horasNoLectivas: 11 },
  33: { horasLectivas: 21, horasNoLectivas: 12 },
  34: { horasLectivas: 22, horasNoLectivas: 12 },
  35: { horasLectivas: 23, horasNoLectivas: 12 },
  36: { horasLectivas: 23, horasNoLectivas: 13 },
  37: { horasLectivas: 24, horasNoLectivas: 13 },
  38: { horasLectivas: 25, horasNoLectivas: 13 },
  39: { horasLectivas: 25, horasNoLectivas: 14 },
  40: { horasLectivas: 26, horasNoLectivas: 14 },
  41: { horasLectivas: 27, horasNoLectivas: 14 },
  42: { horasLectivas: 27, horasNoLectivas: 15 },
  43: { horasLectivas: 28, horasNoLectivas: 15 },
  44: { horasLectivas: 29, horasNoLectivas: 15 },
};
